---
title: "Exercise 1: Correlation"
author: "Stefan Konigorski"
date: "December 9, 2019"
output:
  html_document: default
---

## Load KiGGS data

```{r}
#dat_link <- url("https://www.dropbox.com/s/nbh0f6upejh7nr8/data.RData?dl=1")
#load(dat_link)
load("C:/Users/stefan.konigorski/Desktop/data_Teaching/KiGGS/KiGGS03_06.RData")
dat <- KiGGS03_06
```

## Correlation

Choose 5 different variables and compute pairwise different correlation coefficients. Also look at scatterplots of the variables.

Also try to use the cor and plot for all 5 variables at once.

```{r}
sbp1 <- as.numeric(as.character(dat$sys1))
sbp2 <- as.numeric(as.character(dat$sys2))
sbp12 <- as.numeric(as.character(dat$sys12))

cor(data.frame(sbp1, sbp2, sbp12), use = "complete.obs")
cor(data.frame(sbp1, sbp2, sbp12), use = "complete.obs", method = "pearson")
cor(data.frame(sbp1, sbp2, sbp12), use = "complete.obs", method = "spearman")
cor.test(sbp1, sbp2, use = "complete.obs")

plot(data.frame(sbp1, sbp2, sbp12))

plot(as.numeric(dat$age2),sbp1)
cor(as.numeric(dat$age2), sbp1, use = "complete.obs", method = "spearman")

```

Look at the results (correlation coefficients, confidence intervals, hypothesis tests), compare and interpret them.
